In [1]:
from least_squares import *
import numpy as np

In [6]:
#1)
d= 3
def pol_deg(x, d):
    return np.array([x**i for i in range(d+1)])

data = np.array([1994 + i for i in range(10)])
data = data - 1994
y = np.array([67_052, 68_008, 69_803, 72_024, 73_400, 72_063, 74_669, 74_487, 74_065, 76_777])


A = np.zeros((len(data), 4))
for i in range(len(A)):
    A[i,:] = pol_deg(data[i], d)

x = least_squares(A, y)
print(x)
print("\n\n----------------------")
print((A @ x), f"A @ x, MSE: {sum((A @ x - y) ** 2) / 10}", )

apred = pol_deg(26, d)
print(apred @ x, "prediction")


[ 6.65455483e+04  2.46013947e+03 -3.18229021e+02  1.82130925e+01]


----------------------
[66545.54825175 68705.67179488 70338.61585082 71553.65897436
 72460.07972028 73167.15664336 73784.16829837 74420.3932401
 75185.11002331 76187.5972028 ] A @ x, MSE: 574336.2074358992
235499.66946364933 prediction


In [4]:
A = np.array([[4, 2, 3, 0], 
              [-2, 3, -1, 1], 
              [1, 3, -4, 2], 
              [3, 1, 3, 2]])

Q, R, Y = QR(A, True)
print(Q.T @ Q)
print(np.linalg.norm(Y[:,2]))


[[ 1.00000000e+00  9.02056208e-17  2.49800181e-16  5.55111512e-17]
 [ 9.02056208e-17  1.00000000e+00 -1.38777878e-17 -1.38777878e-16]
 [ 2.49800181e-16 -1.38777878e-17  1.00000000e+00 -1.11022302e-16]
 [ 5.55111512e-17 -1.38777878e-16 -1.11022302e-16  1.00000000e+00]]
4.134905572012118


In [17]:
#3)
def cond(A):
    helper = lambda A: abs(A).sum(axis=1).max()
    return helper(A) * helper(np.linalg.inv(A))

d = 5
ygen = np.vectorize(lambda x: sum(pol_deg(x, d)))

x = np.linspace(1, 4, 12)
ys = ygen(x)
A = np.zeros((12, 6))
# for i in range(len(x)):
A = pol_deg(x, d).T
Q, R = QR(A)
x = least_squares(R, Q.T @ ys)
print(x)
print(cond(R))

[1.00000131 1.00000009 0.99999956 1.00000016 0.99999999 1.        ]
201190.46946346734


In [13]:
#4)

#Answer: 0

#5) F, F, T, F, F
